"""schema inicial

Revision ID: 5ce79500bbe8
Revises: 
Create Date: 2026-08-25 21:51:38.653230

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for nome, valores in (
        ("escopo", ["BOCA", "DENTE", "REGIOES"]),
        (
            "regiao",
            ["MESIAL", "DISTAL", "VESTIBULAR", "LINGUAL", "OCLUSAL",
             "CANAL_MESIAL", "CANAL_CENTRAL", "CANAL_DISTAL"],
        ),
        ("status_lancamento", ["PLANEJADO", "REALIZADO"]),
        (
            "tipo_condicao",
            ["AUSENTE", "RESTAURACAO_ANTERIOR", "COROA", "IMPLANTE", "OUTRO"],
        ),
    ):
        postgresql.ENUM(*valores, name=nome).create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=4), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'codigo')
    )
    op.create_index(op.f('ix_categoria_clinica_id'), 'categoria', ['clinica_id'], unique=False)
    op.create_table('convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=4), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'codigo')
    )
    op.create_index(op.f('ix_convenio_clinica_id'), 'convenio', ['clinica_id'], unique=False)
    op.create_table('pergunta_anamnese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=4), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo_resposta', sa.SmallInteger(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'codigo')
    )
    op.create_index(op.f('ix_pergunta_anamnese_clinica_id'), 'pergunta_anamnese', ['clinica_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_clinica_id'), 'usuario', ['clinica_id'], unique=False)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_clinica_id'), 'auditoria', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_auditoria_criado_em'), 'auditoria', ['criado_em'], unique=False)
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('codigo_legado', sa.String(length=10), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('ci', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('profissao', sa.String(length=60), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('indicacao', sa.String(length=60), nullable=True),
    sa.Column('pai', sa.String(length=120), nullable=True),
    sa.Column('mae', sa.String(length=120), nullable=True),
    sa.Column('convenio_id', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.Date(), nullable=True),
    sa.Column('ultimo_atendimento', sa.Date(), nullable=True),
    sa.Column('revisar_motivo', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paciente_clinica_id'), 'paciente', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_paciente_codigo_legado'), 'paciente', ['codigo_legado'], unique=False)
    op.create_index(op.f('ix_paciente_nome'), 'paciente', ['nome'], unique=False)
    op.create_index(op.f('ix_paciente_ultimo_atendimento'), 'paciente', ['ultimo_atendimento'], unique=False)
    op.create_table('procedimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('escopo_sugerido', postgresql.ENUM(name="escopo", create_type=False), nullable=False),
    sa.Column('regioes_sugeridas', postgresql.ARRAY(postgresql.ENUM(name="regiao", create_type=False)), server_default='{}', nullable=False),
    sa.Column('duracao_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'codigo')
    )
    op.create_index(op.f('ix_procedimento_categoria_id'), 'procedimento', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_procedimento_clinica_id'), 'procedimento', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_procedimento_codigo'), 'procedimento', ['codigo'], unique=False)
    op.create_table('observacao_clinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observacao_clinica_paciente_id'), 'observacao_clinica', ['paciente_id'], unique=False)
    op.create_table('odontograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.SmallInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id', 'numero')
    )
    op.create_index(op.f('ix_odontograma_paciente_id'), 'odontograma', ['paciente_id'], unique=False)
    op.create_table('paciente_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('logradouro', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=60), nullable=True),
    sa.Column('cidade', sa.String(length=60), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paciente_endereco_paciente_id'), 'paciente_endereco', ['paciente_id'], unique=False)
    op.create_table('paciente_telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=24), nullable=False),
    sa.Column('numero_original', sa.String(length=60), nullable=True),
    sa.Column('principal', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paciente_telefone_paciente_id'), 'paciente_telefone', ['paciente_id'], unique=False)
    op.create_table('preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedimento_id', sa.Integer(), nullable=False),
    sa.Column('convenio_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenio.id'], ),
    sa.ForeignKeyConstraint(['procedimento_id'], ['procedimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preco_convenio_id'), 'preco', ['convenio_id'], unique=False)
    op.create_index(op.f('ix_preco_procedimento_id'), 'preco', ['procedimento_id'], unique=False)
    op.create_table('resposta_anamnese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('respondido_em', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta_anamnese.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id', 'pergunta_id')
    )
    op.create_index(op.f('ix_resposta_anamnese_paciente_id'), 'resposta_anamnese', ['paciente_id'], unique=False)
    op.create_table('condicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odontograma_id', sa.Integer(), nullable=False),
    sa.Column('dente', sa.SmallInteger(), nullable=False),
    sa.Column('tipo', postgresql.ENUM(name="tipo_condicao", create_type=False), nullable=False),
    sa.Column('regioes', postgresql.ARRAY(postgresql.ENUM(name="regiao", create_type=False)), server_default='{}', nullable=False),
    sa.Column('icone_legado', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['odontograma_id'], ['odontograma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condicao_icone_legado'), 'condicao', ['icone_legado'], unique=False)
    op.create_index(op.f('ix_condicao_odontograma_id'), 'condicao', ['odontograma_id'], unique=False)
    op.create_table('lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('odontograma_id', sa.Integer(), nullable=False),
    sa.Column('dente', sa.SmallInteger(), nullable=True),
    sa.Column('escopo', postgresql.ENUM(name="escopo", create_type=False), nullable=False),
    sa.Column('procedimento_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM(name="status_lancamento", create_type=False), nullable=False),
    sa.Column('data_planejada', sa.Date(), nullable=True),
    sa.Column('data_realizada', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('codigo_legado', sa.String(length=20), nullable=True),
    sa.Column('revisar_motivo', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(escopo = 'BOCA') = (dente IS NULL)", name='ck_lancamento_dente_conforme_escopo'),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['odontograma_id'], ['odontograma.id'], ),
    sa.ForeignKeyConstraint(['procedimento_id'], ['procedimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamento_clinica_id'), 'lancamento', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_lancamento_codigo_legado'), 'lancamento', ['codigo_legado'], unique=False)
    op.create_index(op.f('ix_lancamento_data_planejada'), 'lancamento', ['data_planejada'], unique=False)
    op.create_index(op.f('ix_lancamento_data_realizada'), 'lancamento', ['data_realizada'], unique=False)
    op.create_index(op.f('ix_lancamento_odontograma_id'), 'lancamento', ['odontograma_id'], unique=False)
    op.create_index(op.f('ix_lancamento_procedimento_id'), 'lancamento', ['procedimento_id'], unique=False)
    op.create_table('lancamento_regiao',
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.Column('regiao', postgresql.ENUM(name="regiao", create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento.id'], ),
    sa.PrimaryKeyConstraint('lancamento_id', 'regiao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamento_regiao')
    op.drop_index(op.f('ix_lancamento_procedimento_id'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_odontograma_id'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_data_realizada'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_data_planejada'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_codigo_legado'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_clinica_id'), table_name='lancamento')
    op.drop_table('lancamento')
    op.drop_index(op.f('ix_condicao_odontograma_id'), table_name='condicao')
    op.drop_index(op.f('ix_condicao_icone_legado'), table_name='condicao')
    op.drop_table('condicao')
    op.drop_index(op.f('ix_resposta_anamnese_paciente_id'), table_name='resposta_anamnese')
    op.drop_table('resposta_anamnese')
    op.drop_index(op.f('ix_preco_procedimento_id'), table_name='preco')
    op.drop_index(op.f('ix_preco_convenio_id'), table_name='preco')
    op.drop_table('preco')
    op.drop_index(op.f('ix_paciente_telefone_paciente_id'), table_name='paciente_telefone')
    op.drop_table('paciente_telefone')
    op.drop_index(op.f('ix_paciente_endereco_paciente_id'), table_name='paciente_endereco')
    op.drop_table('paciente_endereco')
    op.drop_index(op.f('ix_odontograma_paciente_id'), table_name='odontograma')
    op.drop_table('odontograma')
    op.drop_index(op.f('ix_observacao_clinica_paciente_id'), table_name='observacao_clinica')
    op.drop_table('observacao_clinica')
    op.drop_index(op.f('ix_procedimento_codigo'), table_name='procedimento')
    op.drop_index(op.f('ix_procedimento_clinica_id'), table_name='procedimento')
    op.drop_index(op.f('ix_procedimento_categoria_id'), table_name='procedimento')
    op.drop_table('procedimento')
    op.drop_index(op.f('ix_paciente_ultimo_atendimento'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_nome'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_codigo_legado'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_clinica_id'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_auditoria_criado_em'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_clinica_id'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuario_clinica_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_pergunta_anamnese_clinica_id'), table_name='pergunta_anamnese')
    op.drop_table('pergunta_anamnese')
    op.drop_index(op.f('ix_convenio_clinica_id'), table_name='convenio')
    op.drop_table('convenio')
    op.drop_index(op.f('ix_categoria_clinica_id'), table_name='categoria')
    op.drop_table('categoria')
    op.drop_table('clinica')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for nome in ("tipo_condicao", "status_lancamento", "regiao", "escopo"):
        postgresql.ENUM(name=nome).drop(bind, checkfirst=True)
