"""parcela

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-26 03:35:11.859115

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """As 28.244 parcelas do ARQFAT do Dentalis, e o que a clinica registrar
    daqui para frente. Recebimento e parcela com `pago_em` preenchido."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), server_default='', nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('valor_cobrado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_corrigido', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('juros', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('multa', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('codigo_legado', sa.String(length=40), nullable=True),
    sa.Column('revisar_motivo', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcela_clinica_id'), 'parcela', ['clinica_id'], unique=False)
    op.create_index('ix_parcela_clinica_pago_em', 'parcela', ['clinica_id', 'pago_em'], unique=False)
    op.create_index('ix_parcela_clinica_vencimento', 'parcela', ['clinica_id', 'vencimento'], unique=False)
    op.create_index(op.f('ix_parcela_codigo_legado'), 'parcela', ['codigo_legado'], unique=False)
    op.create_index(op.f('ix_parcela_paciente_id'), 'parcela', ['paciente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcela_paciente_id'), table_name='parcela')
    op.drop_index(op.f('ix_parcela_codigo_legado'), table_name='parcela')
    op.drop_index('ix_parcela_clinica_vencimento', table_name='parcela')
    op.drop_index('ix_parcela_clinica_pago_em', table_name='parcela')
    op.drop_index(op.f('ix_parcela_clinica_id'), table_name='parcela')
    op.drop_table('parcela')
    # ### end Alembic commands ###
